[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
startup_mode = "SimpleFullscreen"
decorations = "Buttonless"

opacity = 1
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18
